"""Disclaimer and limitations of the decision-support assistant."""

DECISION_SUPPORT_BANNER = (
    "⚠️ This output is clinical decision support only and does not constitute a direct diagnosis."
)

FULL_DISCLAIMER_FA = (
    "This content was generated by the barekat decision-support system and is not a substitute for the clinical judgment "
    "of the treating physician, specialized genetic counseling, or official treatment protocols. "
    "Final treatment decisions, prescribing, and disease diagnosis rest solely with a licensed physician. "
    "In case of doubt, consult a geneticist or clinical pharmacologist."
)

SHORT_DISCLAIMER_FA = (
    "Reminder: this report is advisory in nature and is not a definitive diagnosis."
)
