name: barekat-bio
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.12
  - openjdk=17
  - fastqc=0.12.1
  - multiqc=1.25
  - bwa-mem2=2.2.1
  - samtools=1.21
  - gatk4=4.6.1.0
  - snpeff=5.2
  - bcftools=1.21
  - pip
